### ISSUE TITLE
Failed to run custom build command for `openssl-sys-extras v0.7.14`

### ISSUE THREAD

**Issue by avanasear** [rustbaeceans/discordterm#22]
I ran `RUST_BACKTRACE=1 cargo run` and this was the output:
```
   Compiling openssl-sys-extras v0.7.14
   Compiling openssl v0.7.14
   Compiling rand v0.3.23
   Compiling tui v0.2.3
   Compiling hpack v0.2.0
   Compiling mime v0.2.6
   Compiling num-integer v0.1.41
   Compiling syn v0.15.42
   Compiling sodiumoxide v0.0.12
error: failed to run custom build command for `openssl-sys-extras v0.7.14`

Caused by:
  process didn't exit successfully: `/home/alucard/builds/discordterm/target/debug/build/openssl-sys-extras-569bce7032713ed7/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-o" "/home/alucard/builds/discordterm/target/debug/build/openssl-sys-extras-28b87e3d3c3ef277/out/src/openssl_shim.o" "-c" "src/openssl_shim.c"
cargo:warning=src/openssl_shim.c: In function ‘SSL_CTX_set_ecdh_auto_shim’:
cargo:warning=src/openssl_shim.c:121:41: warning: unused parameter ‘ctx’ [-Wunused-parameter]
cargo:warning=  121 | int SSL_CTX_set_ecdh_auto_shim(SSL_CTX *ctx, int onoff) {
cargo:warning=      |                                ~~~~~~~~~^~~
cargo:warning=src/openssl_shim.c: In function ‘DH_new_from_params’:
cargo:warning=src/openssl_shim.c:132:7: error: dereferencing pointer to incomplete type ‘DH’ {aka ‘struct dh_st’}
cargo:warning=  132 |     dh->p = p;
cargo:warning=      |       ^~
cargo:warning=src/openssl_shim.c: In function ‘X509_get_extensions_shim’:
cargo:warning=src/openssl_shim.c:143:13: error: dereferencing pointer to incomplete type ‘X509’ {aka ‘struct x509_st’}
cargo:warning=  143 |     return x->cert_info ? x->cert_info->extensions : NULL;
cargo:warning=      |             ^~
cargo:warning=src/openssl_shim.c:144:1: warning: control reaches end of non-void function [-Wreturn-type]
cargo:warning=  144 | }
cargo:warning=      | ^
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall"
"-Wextra" "-o" "/home/alucard/builds/discordterm/target/debug/build/openssl-sys-extras-28b87e3d3c3ef277/out/src/openssl_shim.o" "-c" "src/openssl_shim.c" with args "cc" did not execute successfully (status code exit code: 1).

', /home/alucard/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:1672:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: std::panicking::begin_panic_fmt
   7: gcc::fail
             at /home/alucard/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:1672
   8: gcc::Build::compile
             at /home/alucard/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:785
   9: build_script_build::main
             at ./build.rs:19
  10: std::rt::lang_start::{{closure}}
             at /build/rust/src/rustc-1.36.0-src/src/libstd/rt.rs:64
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start_internal
  14: std::rt::lang_start
             at /build/rust/src/rustc-1.36.0-src/src/libstd/rt.rs:64
  15: main
  16: __libc_start_main
  17: _start

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `openssl v0.7.14`

Caused by:
  process didn't exit successfully: `/home/alucard/builds/discordterm/target/debug/build/openssl-6303d2aded0df56f/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-o" "/home/alucard/builds/discordterm/target/debug/build/openssl-bf45dad9f562eadf/out/src/c_helpers.o" "-c" "src/c_helpers.c"
cargo:warning=src/c_helpers.c: In function ‘rust_SSL_clone’:
cargo:warning=src/c_helpers.c:4:5: warning: implicit declaration of function ‘CRYPTO_add’ [-Wimplicit-function-declaration]
cargo:warning=    4 |     CRYPTO_add(&ssl->references, 1, CRYPTO_LOCK_SSL);
cargo:warning=      |     ^~~~~~~~~~
cargo:warning=src/c_helpers.c:4:20: error: dereferencing pointer to incomplete type ‘SSL’ {aka ‘struct ssl_st’}
cargo:warning=    4 |     CRYPTO_add(&ssl->references, 1, CRYPTO_LOCK_SSL);
cargo:warning=      |                    ^~
cargo:warning=src/c_helpers.c:4:37: error: ‘CRYPTO_LOCK_SSL’ undeclared (first use in this function); did you mean ‘CRYPTO_LOCK’?
cargo:warning=    4 |     CRYPTO_add(&ssl->references, 1, CRYPTO_LOCK_SSL);
cargo:warning=      |                                     ^~~~~~~~~~~~~~~
cargo:warning=      |                                     CRYPTO_LOCK
cargo:warning=src/c_helpers.c:4:37: note: each undeclared identifier is reported only once for each function it
appears in
cargo:warning=src/c_helpers.c: In function ‘rust_SSL_CTX_clone’:
cargo:warning=src/c_helpers.c:8:20: error: dereferencing pointer to incomplete type ‘SSL_CTX’ {aka ‘struct ssl_ctx_st’}
cargo:warning=    8 |     CRYPTO_add(&ctx->references,1,CRYPTO_LOCK_SSL_CTX);
cargo:warning=      |                    ^~
cargo:warning=src/c_helpers.c:8:35: error: ‘CRYPTO_LOCK_SSL_CTX’ undeclared (first use in this function); did you mean ‘CRYPTO_EX_INDEX_SSL_CTX’?
cargo:warning=    8 |     CRYPTO_add(&ctx->references,1,CRYPTO_LOCK_SSL_CTX);
cargo:warning=      |                                   ^~~~~~~~~~~~~~~~~~~
cargo:warning=      |                                   CRYPTO_EX_INDEX_SSL_CTX
cargo:warning=src/c_helpers.c: In function ‘rust_X509_clone’:
cargo:warning=src/c_helpers.c:12:21: error: dereferencing pointer to incomplete type ‘X509’ {aka ‘struct x509_st’}
cargo:warning=   12 |     CRYPTO_add(&x509->references,1,CRYPTO_LOCK_X509);
cargo:warning=      |                     ^~
cargo:warning=src/c_helpers.c:12:36: error: ‘CRYPTO_LOCK_X509’ undeclared (first use in this function); did you
mean ‘CRYPTO_LOCK’?
cargo:warning=   12 |     CRYPTO_add(&x509->references,1,CRYPTO_LOCK_X509);
cargo:warning=      |                                    ^~~~~~~~~~~~~~~~
cargo:warning=      |                                    CRYPTO_LOCK
exit code: 1

--- stderr
thread 'main' panicked at '


Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall"
"-Wextra" "-o" "/home/alucard/builds/discordterm/target/debug/build/openssl-bf45dad9f562eadf/out/src/c_helpers.o" "-c" "src/c_helpers.c" with args "cc" did not execute successfully (status code exit code: 1).

', /home/alucard/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:1672:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: std::panicking::begin_panic_fmt
   7: gcc::fail
             at /home/alucard/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:1672
   8: gcc::Build::compile
             at /home/alucard/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.55/src/lib.rs:785
   9: build_script_build::main
             at ./build.rs:15
  10: std::rt::lang_start::{{closure}}
             at /build/rust/src/rustc-1.36.0-src/src/libstd/rt.rs:64
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start_internal
  14: std::rt::lang_start
             at /build/rust/src/rustc-1.36.0-src/src/libstd/rt.rs:64
  15: main
  16: __libc_start_main
  17: _start

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by avanasear** [comment]
Looks like this is abandoned. Closing
